[build]
  command = "echo 'No build needed'"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Kök istekleri function’a yönlendir
[[redirects]]
  from = "/"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true

[[redirects]]
  from = "/index.html"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
